# -*- coding: utf-8 -*-
"""_TALLER_2_Taller_de_Programacion_en_Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D5_-ST24mmfZh4ScHLGw90NKUt6EGa5a
"""

#Ejercicio 1: Personalizar Mensajes de Bienvenida
def mensaje_bienvenida(edad):
    if edad >= 18:
        print("¡Felicidades! Eres mayor de edad.")
    else:
        años_faltan = 18 - edad
        print(f"Aún eres menor de edad. Te faltan {años_faltan} años para ser mayor.")

# Ejemplo de uso
edad = int(input("Ingresa tu edad: "))
mensaje_bienvenida(edad)

#Ejercicio 2: Determinando la Generación
def determinar_generacion(edad):
    if edad >= 58:
        return "Baby Boomer"
    elif 42 <= edad < 58:
        return "Generación X"
    elif 26 <= edad < 42:
        return "Millennial"
    elif 10 <= edad < 26:
        return "Generación Z"
    else:
        return "Generación Alfa"

def mensaje_bienvenida_con_generacion(edad):
    generacion = determinar_generacion(edad)
    if edad >= 18:
        print(f"¡Felicidades! Eres mayor de edad y perteneces a la {generacion}.")
    else:
        años_faltan = 18 - edad
        print(f"Aún eres menor de edad. Te faltan {años_faltan} años para ser mayor y perteneces a la {generacion}.")

# Ejemplo de uso
edad = int(input("Ingresa tu edad: "))
mensaje_bienvenida_con_generacion(edad)

#Ejercicio 3: Verificar Condiciones Especiales
def es_numero_redondo(edad):
    return edad % 10 == 0

def mensaje_bienvenida_redondo(edad):
    generacion = determinar_generacion(edad)
    if es_numero_redondo(edad):
        print(f"¡Wow! Tienes {edad} años, un número redondo. Perteneces a la {generacion}.")
    elif edad >= 18:
        print(f"¡Felicidades! Eres mayor de edad y perteneces a la {generacion}.")
    else:
        años_faltan = 18 - edad
        print(f"Aún eres menor de edad. Te faltan {años_faltan} años para ser mayor y perteneces a la {generacion}.")

# Ejemplo de uso
edad = int(input("Ingresa tu edad: "))
mensaje_bienvenida_redondo(edad)

#Ejercicio 4: Lista de Contactos
def agregar_contacto(contactos, nombre, telefono):
    contactos[nombre] = telefono

def buscar_contacto(contactos, nombre):
    return contactos.get(nombre, "No se encontró el contacto.")

def mostrar_contactos(contactos):
    for nombre, telefono in contactos.items():
        print(f"Nombre: {nombre}, Teléfono: {telefono}")

def editar_contacto(contactos, nombre, nuevo_telefono):
    if nombre in contactos:
        contactos[nombre] = nuevo_telefono
    else:
        print("No se encontró el contacto.")

# Ejemplo de uso
contactos = {}
while True:
    print("1. Agregar Contacto")
    print("2. Buscar Contacto")
    print("3. Mostrar Contactos")
    print("4. Editar Contacto")
    print("5. Salir")
    opcion = int(input("Elige una opción: "))

    if opcion == 1:
        nombre = input("Ingresa el nombre del contacto: ")
        telefono = input("Ingresa el teléfono del contacto: ")
        agregar_contacto(contactos, nombre, telefono)
    elif opcion == 2:
        nombre = input("Ingresa el nombre del contacto que quieres buscar: ")
        print(buscar_contacto(contactos, nombre))
    elif opcion == 3:
        mostrar_contactos(contactos)
    elif opcion == 4:
        nombre = input("Ingresa el nombre del contacto que quieres editar: ")
        nuevo_telefono = input("Ingresa el nuevo teléfono: ")
        editar_contacto(contactos, nombre, nuevo_telefono)
    elif opcion == 5:
        break
    else:
        print("Opción no válida.")

#Ejercicio 5: Organizando una Fiesta
def agregar_invitado(lista_invitados, nombre):
    lista_invitados.append(nombre)

def eliminar_invitado(lista_invitados, nombre):
    if nombre in lista_invitados:
        lista_invitados.remove(nombre)
    else:
        print("El invitado no está en la lista.")

def verificar_invitado(lista_invitados, nombre):
    return nombre in lista_invitados

def editar_invitado(lista_invitados, nombre_antiguo, nombre_nuevo):
    if nombre_antiguo in lista_invitados:
        index = lista_invitados.index(nombre_antiguo)
        lista_invitados[index] = nombre_nuevo
    else:
        print("El invitado no está en la lista.")

# Ejemplo de uso
lista_invitados = []
while True:
    print("1. Agregar Invitado")
    print("2. Eliminar Invitado")
    print("3. Verificar Invitado")
    print("4. Editar Invitado")
    print("5. Salir")
    opcion = int(input("Elige una opción: "))

    if opcion == 1:
        nombre = input("Ingresa el nombre del invitado: ")
        agregar_invitado(lista_invitados, nombre)
    elif opcion == 2:
        nombre = input("Ingresa el nombre del invitado que quieres eliminar: ")
        eliminar_invitado(lista_invitados, nombre)
    elif opcion == 3:
        nombre = input("Ingresa el nombre del invitado que quieres verificar: ")
        if verificar_invitado(lista_invitados, nombre):
            print(f"{nombre} está en la lista de invitados.")
        else:
            print(f"{nombre} no está en la lista de invitados.")
    elif opcion == 4:
        nombre_antiguo = input("Ingresa el nombre del invitado que quieres editar: ")
        nombre_nuevo = input("Ingresa el nuevo nombre: ")
        editar_invitado(lista_invitados, nombre_antiguo, nombre_nuevo)
    elif opcion == 5:
        break
    else:
        print("Opción no válida.")